### ISSUE TITLE
RF Codes

### ISSUE THREAD

**Issue by GerSant** [ndoty/rf-projector-screen#1]
Can you provide me the RF Codes of the remote? I only have the transmitter ;)

Thanks

**Comment by ndoty** [comment]
Lines 21-22 in the ProjectorScreen433mhz.ino provide the raise and lower commands that come from the remote.

`const long lowerMhz = 2981764; //HomeGear Remote sent this command to lower so let's use it in the code
const long raiseMhz = 2981761; //HomeGear Remote sent this command to raise so let's use it in the code`
